export const wordCategories: Record<string, string[]> = {
  'rappers-czsk': [
    'Rytmus',
    'Ektor',
    'Yzomandias',
    'Nik Tendo',
    'Separ',
    'Hasan',
    'Kato',
    'Rest',
    'Calin',
    'Kontrafakt',
  ],
  'rappers-foreign': [
    'Eminem',
    'Drake',
    'Kendrick Lamar',
    'Travis Scott',
    'Kanye West',
    'Lil Wayne',
    'Snoop Dogg',
    '50 Cent',
  ],
  'streamers-czsk': [
    'Agraelus',
    'Vojtěch',
    'Bax',
    'MenT',
    'Jirka Kral',
    'Kovy',
    'Herdyn',
    'Gejmr',
    'Kovy',
    'Pewdiepie',
  ],
  'streamers-foreign': [
    'xQc',
    'Pokimane',
    'Ninja',
    'Jynxzi',
    'Marlon',
    'Lacy',
  ],
  'clash-royale': [
    'Archers',
    'Baby Dragon',
    'Balloon',
    'Bandit',
    'Barbarians',
    'Bats',
    'Battle Healer',
    'Battle Ram',
    'Bomber',
    'Bowler',
    'Cannon',
    'Cannon Cart',
    'Dark Prince',
    'Electro Dragon',
    'Electro Giant',
    'Electro Spirit',
    'Elite Barbarians',
    'Executioner',
    'Fire Spirit',
    'Firecracker',
    'Fisherman',
    'Flying Machine',
    'Giant',
    'Giant Skeleton',
    'Goblin Barrel',
    'Goblin Cage',
    'Goblin Gang',
    'Goblin Giant',
    'Goblin Hut',
    'Goblins',
    'Golden Knight',
    'Golem',
    'Graveyard',
    'Guards',
    'Hog Rider',
    'Hunter',
    'Ice Golem',
    'Ice Spirit',
    'Ice Wizard',
    'Inferno Dragon',
    'Inferno Tower',
    'Knight',
    'Lava Hound',
    'Lumberjack',
    'Magic Archer',
    'Mega Knight',
    'Mega Minion',
    'Miner',
    'Mini P.E.K.K.A',
    'Minions',
    'Mortar',
    'Mother Witch',
    'Musketeer',
    'Night Witch',
    'P.E.K.K.A',
    'Prince',
    'Princess',
    'Ram Rider',
    'Royal Delivery',
    'Royal Ghost',
    'Royal Giant',
    'Royal Hogs',
    'Royal Recruits',
    'Skeleton Army',
    'Skeleton Barrel',
    'Skeleton Dragons',
    'Skeleton King',
    'Skeletons',
    'Sparky',
    'Spear Goblins',
    'Tesla',
    'Three Musketeers',
    'Tombstone',
    'Valkyrie',
    'Wall Breakers',
    'Witch',
    'Wizard',
    'X-Bow',
    'Zappies'
  ],
};

export function getRandomWord(category: string, customWords?: string[]): string {
  if (customWords && customWords.length > 0) {
    return customWords[Math.floor(Math.random() * customWords.length)];
  }
  
  const words = wordCategories[category];
  if (!words || words.length === 0) {
    return 'Slovo';
  }
  
  return words[Math.floor(Math.random() * words.length)];
}